test:test.cpp filetrick.hpp httplib.h net_sv.hpp
		g++ -o $@ $^ -lpthread -lstdc++fs -ljsoncpp -I/usr/local/openssl-3.3.1/include -L/usr/local/openssl-3.3.1/lib64 -DCPPHTTPLIB_OPENSSL_SUPPORT -lssl -lcrypto
